
const PageBanner = () =>{

    return(
        <>
        <title>Tester Lage Next app for B4N.codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

</>
    )
}

export default PageBanner;